name: ci
on:
  push:
    branches:
      - main

jobs:
  asciidoctor_job:
    runs-on: self-hosted
    name: Build AsciiDoctor
    steps:
    - name: Check out code
      uses: actions/checkout@v3